---
kind: pipeline
type: docker
name: default

steps:
  - name: submodules
    image: docker:git
    commands:
      - git config submodule.secret.url https://${GIT_USERNAME}:${GIT_PASSWORD}@zxq.co/ripple/old-frontend-secret.git
      - git submodule update --init --recursive
    secrets: [ git_username, git_password ]

  - name: prepare-docker
    image: docker:git
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
      - git clone https://zxq.co/ripple/dockerfiles /dockerfiles
      - date +"%Y%m%d." | tr -d '\n' > .tags
      - echo $DRONE_BUILD_NUMBER >> .tags
      - cp /dockerfiles/dockerfiles/o9d.Dockerfile Dockerfile
    volumes:
      - name: cache
        path: /cache

  - name: package-docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: d.nyodev.xyz
      repo: d.nyodev.xyz/ripple/o9d
      use_cache: true
    secrets: [ docker_username, docker_password ]
    volumes:
      - name: docker
        path: /var/lib/docker

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker
